# Generated by Django 4.1.5 on 2023-01-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=250)),
                ('product_description', models.TextField(blank=True, db_index=True)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
