# Generated by Django 4.1.6 on 2023-02-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
    ]
